project_id: '459244'
pull_request_title: "Crowdin Translation Updates [Automatic PR]"

files:
  - source: /plugin/src/main/resources/language/en_us.lang.yml
    translation: /plugin/src/main/resources/language/%locale_with_underscore%.lang.yml
