name: Expansion Request
description: Make a suggestion for a new plugin compatibility expansion.
labels:
  - Feature Request

body:
  - type: markdown
    attributes:
      value: |-
        Please fill out the following form to the best of your ability.
        The better you fill this out, the faster we can resolve the problem.

  - type: dropdown
    attributes:
      label: Server Implementation
      description: >-
        Which server implementation are you using? If your server implementation
        is not listed, we do not provide support for it.
      multiple: false
      options:
        - Spigot
        - Paper
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Server Version
      description: >-
        Which server version are you using? If your version is not listed, we do
        not provide support for it.
      multiple: false
      options:
        - 1.8.8
        - 1.12.2
        - 1.16.5
        - 1.18.2
        - 1.19.3
    validations:
      required: true

  - type: textarea
    attributes:
      label: CombatLogX Version
      description: >-
        Please run the command '/clx version' on your server and post the output
        here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Plugin
      description: >-
        Which plugin needs a compatibility expansion? Please provide a link to
        the plugin. We also need access to source or an API jar.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Explanation
      description: >-
        Please explain why this plugin needs support or how we can improve the
        support for this plugin.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Extra Information
      description: What other information (if any) do you need us to know?
